version: 2.1

jobs:
  build:
    working_directory: ~/digital-twin-builder-gltf-layer
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - attach_workspace:
          at: ~/digital-twin-builder-gltf-layer
      - run:
          name: make to build
          command: |
            make -f ./Makefile-deploy
      - persist_to_workspace:
          root: ~/digital-twin-builder-gltf-layer
          paths:
            - ./*

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          # context:
          #   - master-account-deployment
          #   - aws-default-region
          filters:
            branches:
              only:
                - /^(staging|main|epic\/)(.*)$/
